### ISSUE TITLE
Bad substitution error running kubectl ssh on Ubuntu

### ISSUE THREAD

**Issue by cormachogan** [containership/kubectl-cssh#23]
### Description

When I try to run kubectl cssh (after installing plugin using krew), it consistently fails with a Bad substitution error

#### What is the current behavior?

$ kubectl krew list
PLUGIN    VERSION
change-ns afbb3278d21b3e3ad540de6e6022d802352758d69dbf2d9a43828b2b8e43ef07
cssh      c638dcc802d2d52ce0ec2283a2f9d217eaa17855f3edd702229571da39c1ab84
krew      dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a

$ kubectl cssh
/home/cormac/.krew/bin/kubectl-cssh: 7: /home/cormac/.krew/bin/kubectl-cssh: Bad substitution

$ kubectl cssh --help
/home/cormac/.krew/bin/kubectl-cssh: 7: /home/cormac/.krew/bin/kubectl-cssh: Bad substitution
cormac@pks-cli:~$

#### Additional Context

$ uname -a
Linux pks-cli.rainpole.com 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:10:00Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
cormac@pks-cli:~$

$ kubectl krew info cssh
NAME: cssh
URI: https://github.com/containership/kubectl-cssh/archive/v1.0.0.tar.gz
SHA256: c638dcc802d2d52ce0ec2283a2f9d217eaa17855f3edd702229571da39c1ab84
DESCRIPTION:
This plugin allows users to SSH into one more more Kubernetes nodes
within separate tmux panes.

VERSION: v1.0.0
CAVEATS:
\
 |  This plugin needs the following programs:
 |  * tmux
/
cormac@pks-cli:~$

### Reproduction
1. Run the command '...'
2. ...

### Evidence
If applicable, add logs or screenshots to help explain your problem.

**Comment by mmack** [comment]
Same here.

**Comment by normanjoyner** [comment]
Tracking merge into krew index [here](
https://github.com/GoogleContainerTools/krew-index/pull/76), but the issue should be fixed on master.
