### ISSUE TITLE
error while connecting to tmux on macOS

### ISSUE THREAD

**Issue by ahmetb** [containership/kubectl-cssh#6]
I just got this error first time I installed tmux (no tmux session):

```
error connecting to /private/tmp/tmux-445605/default (No such file or directory)
Failed to connect to tmux session.
``` 
because

```
$ tmux ls
no server running on /private/tmp/tmux-445605/default
```

Then I got a tmux session but detached from it.

Then I ran `tmux ssh` it exited without any message, then I realized it actually did the connection on tmux session (I think this part should be documented heavily).

**Comment by normanjoyner** [comment]
This caveat still needs documented.
